### ISSUE TITLE
Problem help

### ISSUE THREAD

**Issue by cpa-3** [o-messai/3D-NR-SIQA#1]
Excuse me, I am a student related to quality evaluation. I have the honor to read your paper on quality evaluation. It seems that the code you provided lacks some sub functions, such as crop_ Saliency_ Percentage and concatenate_ Data and predict. Is it convenient to provide it? Thank you very much!

**Comment by o-messai** [comment]
Sorry for the missing functions ! It should work now. Please let me know if you face any other problems.

**Comment by cpa-3** [comment]
Hello, sir. It's my honor to read your paper. I want to try your method in my research direction, but I have a few questions. I hope you can answer them. First of all, how to determine the maximum disparity distance? Different data sets are different, so is it determined through multiple experiments? Secondly, there is a little distortion after fusion. Will this affect the experimental results? Or how to avoid such distortion? Thank you very much for your reading
| |
陈平安
|
|
***@***.***
|
---- Replied Message ----
| From | Oussama ***@***.***> |
| Date | 6/16/2022 21:05 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [o-messai/3D-NR-SIQA] Problem help (Issue #1) |

Sorry for the missing functions ! It should work now. Please let me know if you face any other problems.

**Comment by o-messai** [comment]
Hi, thank you for your good questions,

1- We have fixed the disparity manually for all datasets to be 25 (if I remember correctly). It depends on the image resolution, you may increase the max. disparity for higher resolution to get better estimation, but we have conducted some tests and found that fixing it for all datasets is not bad.

2- The distortions after fusion is more likely caused by the disparity map, and it actually does not effect much the results since we process the whole cyclopean image and the other distortion will be dominant (i,e., jpeg, WN, etc.), but even if it effects the results it should be in a good way: **the distortion in stereo=>cause bad depth information=> cause bad fusion=> bad quality.** 

**I hope the arrows below resumes my answer:**
Distorted stereo image=>bad disparity map **=>** bad depth information perceived by the viewer (using stereo glasses)  **=>** bad fusion added little new distortion (but not dominant) **=>** bad cyclopean view inside his brain **=>** bad quality, discomfort and maybe headache.

Anyway if you want to avoid the added little distortion, you need to fine tune the parameters of the process (like disp. max).

**Comment by cpa-3** [comment]
OK, thank you for your answers.






| |
陈平安
|
|
***@***.***
|
---- Replied Message ----
| From | Oussama ***@***.***> |
| Date | 10/20/2022 16:44 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [o-messai/3D-NR-SIQA] Problem help (Issue #1) |

Hi, thank you for your good questions,

1- We have fixed the disparity manually for all datasets to be 25 (if I remember correctly). It depends on the image resolution, you may increase the max. disparity for higher resolution to get better estimation, but we have conducted some tests and found that fixing it for all datasets is not bad.

2- The distortions after fusion is more likely caused by the disparity map, and it actually does not effect much the results since we process the whole cyclopean image and the other distortion will be dominant (i,e., jpeg, WN, etc.), but even if it effects the results it should be in a good way: the distortion in stereo=>cause bad depth information=> cause bad fusion=> bad quality.

I hope the arrows below resumes my answer:
Distorted stereo image=>bad disparity map => bad depth information perceived by the viewer (using stereo glasses) => bad fusion added little new distortion (but not dominant)=> bad cyclopean view inside his brain=> bad quality, discomfort and maybe headache.

Anyway if you want to avoid the added little distortion, you need to fine tuning the parameters of the process (like disp. max).
